name: Convert py files to colab

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.6'
    - name: install jupytext
      run: pip install jupytext
    - name: convert py to ipynb
      run: |
        python py_to_colab.py
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        dir: notebooks
        branch: master
        token: ${{ secrets.ACCESS_TOKEN }}